services:
  postgres_db:
    container_name: 'postgres_db'
    image: postgres:14.7-alpine
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 1s
      timeout: 1s
      retries: 10
    ports:
      - ${DB_PORT}:5432
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
