services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - api-network

  postgres_db:
    container_name: 'postgres_db'
    image: postgres:14.7-alpine
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 1s
      timeout: 1s
      retries: 10
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
